kind: ConfigMap
apiVersion: v1
metadata:
  name: pod-autoscaler-nanny-params
  namespace: default
data:
  simple-scalar.scale-map: |-
    { "cores_to_replicas_map": 
      [
      [ 1,1 ], 
      [ 3,3 ], 
      [ 512,5 ], 
      [ 1024,7 ], 
      [ 2048,10 ], 
      [ 4096,15 ], 
      [ 8192,20 ], 
      [ 12288,30 ], 
      [ 16384,40 ], 
      [ 20480,50 ], 
      [ 24576,60 ], 
      [ 28672,70 ], 
      [ 32768,80 ], 
      [ 65535,100 ]
      ],
      "nodes_to_replicas_map": 
        [
        [ 1,1 ], 
        [ 2,2 ]
        ]
    }
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: pod-autoscaler-nanny
  namespace: default
  labels:
    version: v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        version: v1
    spec:
      containers:
        - image: gcr.io/google_containers/cluster-proportional-autoscaler:0.6
          imagePullPolicy: Always
          name: cluster-proportional-autoscaler
          command:
            - /cluster-proportional-autoscaler
            - --namespace=default
            - --configmap=dns-cluster-proportional-autoscaler-params
            - --rc=pod-autoscaler-nanny
            - --verbose
